name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - tests-on-ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test-unit
