name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_HOST: ${{ secrets.NODE_HOST }}
      NODE_PORT: ${{ secrets.NODE_PORT }}
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          if [ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]; then
            echo "PR is from a fork, running unit tests..."
            npm run test-unit
          else
            echo "PR is not from a fork, running all tests..."
            npm run test
          fi
